# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
docker_packages:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"

docker_python_packages:
  - "docker"
  - "pyOpenSSL"
  # Requests 2.32.3 breaks Docker Python and community.docker modules. The error is:
  # "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"
  # See https://github.com/docker/docker-py/issues/3256
  - "requests>=2.31,<2.32"
